[[images]]
distro = "almalinux"
version = "8"
arch = "AMD64"
base_url = "https://raw.repo.almalinux.org/almalinux/8/cloud/x86_64/images/"
image_file = "AlmaLinux-8-GenericCloud-latest.x86_64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 1622540288

[[images]]
distro = "almalinux"
version = "8"
arch = "ARM64"
base_url = "https://raw.repo.almalinux.org/almalinux/8/cloud/aarch64/images/"
image_file = "AlmaLinux-8-GenericCloud-latest.aarch64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 1487208448

[[images]]
distro = "almalinux"
version = "9"
arch = "AMD64"
base_url = "https://raw.repo.almalinux.org/almalinux/9/cloud/x86_64/images/"
image_file = "AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 589299712

[[images]]
distro = "almalinux"
version = "9"
arch = "ARM64"
base_url = "https://raw.repo.almalinux.org/almalinux/9/cloud/aarch64/images/"
image_file = "AlmaLinux-9-GenericCloud-latest.aarch64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 451543040

[[images]]
distro = "almalinux"
version = "10"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://raw.repo.almalinux.org/almalinux/10/cloud/x86_64/images/"
image_file = "AlmaLinux-10-GenericCloud-latest.x86_64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 496631808

[[images]]
distro = "almalinux"
version = "10"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://raw.repo.almalinux.org/almalinux/10/cloud/aarch64/images/"
image_file = "AlmaLinux-10-GenericCloud-latest.aarch64.qcow2"
checksum_file = "CHECKSUM"
hash_alg = "Sha256"
size = 442433536

[[images]]
distro = "alpine"
version = "3.21"
arch = "AMD64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/cloud/"
image_file = "alpine-3.21.8-x86_64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.21.8-x86_64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 179961856

[[images]]
distro = "alpine"
version = "3.21"
arch = "ARM64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/cloud/"
image_file = "alpine-3.21.8-aarch64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.21.8-aarch64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 208601088

[[images]]
distro = "alpine"
version = "3.22"
arch = "AMD64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/"
image_file = "alpine-3.22.6-x86_64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.22.6-x86_64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 188547072

[[images]]
distro = "alpine"
version = "3.22"
arch = "ARM64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/"
image_file = "alpine-3.22.6-aarch64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.22.6-aarch64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 209387520

[[images]]
distro = "alpine"
version = "3.23"
arch = "AMD64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/"
image_file = "alpine-3.23.6-x86_64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.23.6-x86_64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 199426048

[[images]]
distro = "alpine"
version = "3.23"
arch = "ARM64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/"
image_file = "alpine-3.23.6-aarch64-uefi-cloudinit-r0.qcow2"
checksum_file = "alpine-3.23.6-aarch64-uefi-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 248119296

[[images]]
distro = "alpine"
version = "3.24"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/cloud/"
image_file = "alpine-3.24.2-x86_64-cloudinit-r0.qcow2"
checksum_file = "alpine-3.24.2-x86_64-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 175636480

[[images]]
distro = "alpine"
version = "3.24"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/cloud/"
image_file = "alpine-3.24.2-aarch64-cloudinit-r0.qcow2"
checksum_file = "alpine-3.24.2-aarch64-cloudinit-r0.qcow2.sha512"
hash_alg = "Sha512"
size = 203161600

[[images]]
distro = "archlinux"
version = "rolling"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://geo.mirror.pkgbuild.com/images/latest/"
image_file = "Arch-Linux-x86_64-cloudimg.qcow2"
checksum_file = "Arch-Linux-x86_64-cloudimg.qcow2.SHA256"
hash_alg = "Sha256"
size = 559367680

[[images]]
distro = "centos"
version = "10"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://cloud.centos.org/centos/10-stream/x86_64/images/"
image_file = "CentOS-Stream-GenericCloud-10-*.x86_64.qcow2"
checksum_file = "{image_file}.SHA256SUM"
hash_alg = "Sha256"
size = 1045037056

[[images]]
distro = "centos"
version = "10"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://cloud.centos.org/centos/10-stream/aarch64/images/"
image_file = "CentOS-Stream-GenericCloud-10-*.aarch64.qcow2"
checksum_file = "{image_file}.SHA256SUM"
hash_alg = "Sha256"
size = 884277248

[[images]]
distro = "debian"
version = "10"
codename = "buster"
arch = "AMD64"
base_url = "https://cloud.debian.org/images/cloud/buster/latest/"
image_file = "debian-10-generic-amd64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 316402176
eol = true

[[images]]
distro = "debian"
version = "10"
codename = "buster"
arch = "ARM64"
base_url = "https://cloud.debian.org/images/cloud/buster/latest/"
image_file = "debian-10-generic-arm64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 303853568
eol = true

[[images]]
distro = "debian"
version = "11"
codename = "bullseye"
arch = "AMD64"
base_url = "https://cloud.debian.org/images/cloud/bullseye/latest/"
image_file = "debian-11-generic-amd64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 365428736

[[images]]
distro = "debian"
version = "11"
codename = "bullseye"
arch = "ARM64"
base_url = "https://cloud.debian.org/images/cloud/bullseye/latest/"
image_file = "debian-11-generic-arm64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 331546624

[[images]]
distro = "debian"
version = "12"
codename = "bookworm"
arch = "AMD64"
base_url = "https://cloud.debian.org/images/cloud/bookworm/latest/"
image_file = "debian-12-generic-amd64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 449314816

[[images]]
distro = "debian"
version = "12"
codename = "bookworm"
arch = "ARM64"
base_url = "https://cloud.debian.org/images/cloud/bookworm/latest/"
image_file = "debian-12-generic-arm64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 435683328

[[images]]
distro = "debian"
version = "13"
codename = "trixie"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://cloud.debian.org/images/cloud/trixie/latest/"
image_file = "debian-13-generic-amd64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 433651712

[[images]]
distro = "debian"
version = "13"
codename = "trixie"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://cloud.debian.org/images/cloud/trixie/latest/"
image_file = "debian-13-generic-arm64.qcow2"
checksum_file = "SHA512SUMS"
hash_alg = "Sha512"
size = 431685632

[[images]]
distro = "fedora"
version = "43"
arch = "AMD64"
base_url = "https://dl.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/"
image_file = "Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2"
checksum_file = "Fedora-Cloud-43-1.6-x86_64-CHECKSUM"
hash_alg = "Sha256"
size = 583335936

[[images]]
distro = "fedora"
version = "43"
arch = "ARM64"
base_url = "https://dl.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/aarch64/images/"
image_file = "Fedora-Cloud-Base-Generic-43-1.6.aarch64.qcow2"
checksum_file = "Fedora-Cloud-43-1.6-aarch64-CHECKSUM"
hash_alg = "Sha256"
size = 544997376

[[images]]
distro = "fedora"
version = "44"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://dl.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/"
image_file = "Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"
checksum_file = "Fedora-Cloud-44-1.7-x86_64-CHECKSUM"
hash_alg = "Sha256"
size = 583729152

[[images]]
distro = "fedora"
version = "44"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://dl.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/aarch64/images/"
image_file = "Fedora-Cloud-Base-Generic-44-1.7.aarch64.qcow2"
checksum_file = "Fedora-Cloud-44-1.7-aarch64-CHECKSUM"
hash_alg = "Sha256"
size = 528154624

[[images]]
distro = "gentoo"
version = "rolling"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://distfiles.gentoo.org/releases/amd64/autobuilds/current-di-amd64-cloudinit/"
image_file = "di-amd64-cloudinit-*.qcow2"
checksum_file = "{image_file}.sha256"
hash_alg = "Sha256"
size = 1200160768

[[images]]
distro = "gentoo"
version = "rolling"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://distfiles.gentoo.org/releases/arm64/autobuilds/current-di-arm64-cloudinit/"
image_file = "di-arm64-cloudinit-*.qcow2"
checksum_file = "{image_file}.sha256"
hash_alg = "Sha256"
size = 1187643392

[[images]]
distro = "opensuse-leap"
version = "15.6"
arch = "AMD64"
base_url = "https://downloadcontent.opensuse.org/distribution/leap/15.6/appliances/"
image_file = "openSUSE-Leap-15.6-Minimal-VM.x86_64-Cloud.qcow2"
checksum_file = "openSUSE-Leap-15.6-Minimal-VM.x86_64-Cloud.qcow2.sha256"
hash_alg = "Sha256"
size = 276980736

[[images]]
distro = "opensuse-leap"
version = "15.6"
arch = "ARM64"
base_url = "https://downloadcontent.opensuse.org/distribution/leap/15.6/appliances/"
image_file = "openSUSE-Leap-15.6-Minimal-VM.aarch64-Cloud.qcow2"
checksum_file = "openSUSE-Leap-15.6-Minimal-VM.aarch64-Cloud.qcow2.sha256"
hash_alg = "Sha256"
size = 265008640

[[images]]
distro = "opensuse-leap"
version = "16.0"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://downloadcontent.opensuse.org/distribution/leap/16.0/appliances/"
image_file = "Leap-16.0-Minimal-VM.x86_64-Cloud.qcow2"
checksum_file = "Leap-16.0-Minimal-VM.x86_64-Cloud.qcow2.sha256"
hash_alg = "Sha256"
size = 337845760

[[images]]
distro = "opensuse-leap"
version = "16.0"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://downloadcontent.opensuse.org/distribution/leap/16.0/appliances/"
image_file = "Leap-16.0-Minimal-VM.aarch64-Cloud.qcow2"
checksum_file = "Leap-16.0-Minimal-VM.aarch64-Cloud.qcow2.sha256"
hash_alg = "Sha256"
size = 318721536

[[images]]
distro = "rockylinux"
version = "8"
arch = "AMD64"
base_url = "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/"
image_file = "Rocky-8-GenericCloud-Base.latest.x86_64.qcow2"
checksum_file = "Rocky-8-GenericCloud-Base.latest.x86_64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 2065760256

[[images]]
distro = "rockylinux"
version = "8"
arch = "ARM64"
base_url = "https://dl.rockylinux.org/pub/rocky/8/images/aarch64/"
image_file = "Rocky-8-GenericCloud-Base.latest.aarch64.qcow2"
checksum_file = "Rocky-8-GenericCloud-Base.latest.aarch64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 1925644288

[[images]]
distro = "rockylinux"
version = "9"
arch = "AMD64"
base_url = "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/"
image_file = "Rocky-9-GenericCloud-Base.latest.x86_64.qcow2"
checksum_file = "Rocky-9-GenericCloud-Base.latest.x86_64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 645988352

[[images]]
distro = "rockylinux"
version = "9"
arch = "ARM64"
base_url = "https://dl.rockylinux.org/pub/rocky/9/images/aarch64/"
image_file = "Rocky-9-GenericCloud-Base.latest.aarch64.qcow2"
checksum_file = "Rocky-9-GenericCloud-Base.latest.aarch64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 519831552

[[images]]
distro = "rockylinux"
version = "10"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://dl.rockylinux.org/pub/rocky/10/images/x86_64/"
image_file = "Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
checksum_file = "Rocky-10-GenericCloud-Base.latest.x86_64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 544997376

[[images]]
distro = "rockylinux"
version = "10"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://dl.rockylinux.org/pub/rocky/10/images/aarch64/"
image_file = "Rocky-10-GenericCloud-Base.latest.aarch64.qcow2"
checksum_file = "Rocky-10-GenericCloud-Base.latest.aarch64.qcow2.CHECKSUM"
hash_alg = "Sha256"
size = 469368832

[[images]]
distro = "ubuntu"
version = "18.04"
codename = "bionic"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/bionic/release/"
image_file = "ubuntu-18.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 216006656
eol = true

[[images]]
distro = "ubuntu"
version = "18.10"
codename = "cosmic"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/cosmic/release/"
image_file = "ubuntu-18.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 303759360
eol = true

[[images]]
distro = "ubuntu"
version = "19.04"
codename = "disco"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/disco/release/"
image_file = "ubuntu-19.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 160759808
eol = true

[[images]]
distro = "ubuntu"
version = "19.10"
codename = "eoan"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/eoan/release/"
image_file = "ubuntu-19.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 202506240
eol = true

[[images]]
distro = "ubuntu"
version = "20.04"
codename = "focal"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/focal/release/"
image_file = "ubuntu-20.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 264175616
eol = true

[[images]]
distro = "ubuntu"
version = "20.10"
codename = "groovy"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/groovy/release/"
image_file = "ubuntu-20.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 262799360
eol = true

[[images]]
distro = "ubuntu"
version = "21.04"
codename = "hirsute"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/hirsute/release/"
image_file = "ubuntu-21.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 270860288
eol = true

[[images]]
distro = "ubuntu"
version = "21.10"
codename = "impish"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/impish/release/"
image_file = "ubuntu-21.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 266731520
eol = true

[[images]]
distro = "ubuntu"
version = "22.04"
codename = "jammy"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/jammy/release/"
image_file = "ubuntu-22.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 310239744

[[images]]
distro = "ubuntu"
version = "22.10"
codename = "kinetic"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/kinetic/release/"
image_file = "ubuntu-22.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 308805632
eol = true

[[images]]
distro = "ubuntu"
version = "23.04"
codename = "lunar"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/lunar/release/"
image_file = "ubuntu-23.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 352190464
eol = true

[[images]]
distro = "ubuntu"
version = "23.10"
codename = "mantic"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/mantic/release/"
image_file = "ubuntu-23.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 239140864
eol = true

[[images]]
distro = "ubuntu"
version = "23.10"
codename = "mantic"
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/mantic/release/"
image_file = "ubuntu-23.10-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 216268800
eol = true

[[images]]
distro = "ubuntu"
version = "24.04"
codename = "noble"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/noble/release/"
image_file = "ubuntu-24.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 264372224

[[images]]
distro = "ubuntu"
version = "24.04"
codename = "noble"
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/noble/release/"
image_file = "ubuntu-24.04-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 229113856

[[images]]
distro = "ubuntu"
version = "24.10"
codename = "oracular"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/oracular/release/"
image_file = "ubuntu-24.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 261685248
eol = true

[[images]]
distro = "ubuntu"
version = "24.10"
codename = "oracular"
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/oracular/release/"
image_file = "ubuntu-24.10-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 230752256
eol = true

[[images]]
distro = "ubuntu"
version = "25.04"
codename = "plucky"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/plucky/release/"
image_file = "ubuntu-25.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 273809408
eol = true

[[images]]
distro = "ubuntu"
version = "25.04"
codename = "plucky"
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/plucky/release/"
image_file = "ubuntu-25.04-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 242352128
eol = true

[[images]]
distro = "ubuntu"
version = "25.10"
codename = "questing"
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/questing/release/"
image_file = "ubuntu-25.10-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 413325312

[[images]]
distro = "ubuntu"
version = "25.10"
codename = "questing"
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/questing/release/"
image_file = "ubuntu-25.10-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 390922240

[[images]]
distro = "ubuntu"
version = "26.04"
codename = "resolute"
tags = ["stable", "latest"]
arch = "AMD64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/resolute/release/"
image_file = "ubuntu-26.04-minimal-cloudimg-amd64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 427574784

[[images]]
distro = "ubuntu"
version = "26.04"
codename = "resolute"
tags = ["stable", "latest"]
arch = "ARM64"
base_url = "https://cloud-images.ubuntu.com/minimal/releases/resolute/release/"
image_file = "ubuntu-26.04-minimal-cloudimg-arm64.img"
checksum_file = "SHA256SUMS"
hash_alg = "Sha256"
size = 408606720
