[package]
name = "cubic"
version = "0.2.0"
authors = ["Roger Knecht <rknecht@pm.me>"]
license = "GPL-2.0-only"
description = """\
Cubic is a lightweight command line manager for virtual machines. It has a
simple, daemon-less and rootless design. All Cubic virtual machines run
isolated in the user context. Cubic is built on top of QEMU, KVM and cloud-init.

Show all supported images:
$ cubic image list --all

Create a new virtual machine instance:
$ cubic instance add --name mymachine --image ubuntu:noble

List all virtual machine instances:
$ cubic list

Start an instance:
$ cubic start <instance name>

Stop an instance:
$ cubic stop <instance name>

Open a shell in the instance:
$ cubic ssh <machine name>

Copy a file from the host to the instance:
$ cubic scp <path/to/host/file> <machine>:<path/to/guest/file>

Copy a file from the instance to the hots:
$ cubic scp <machine>:<path/to/guest/file> <path/to/host/file>
"""
readme = "README.md"
homepage = "https://github.com/cubic-vm/cubic"
repository = "https://github.com/cubic-vm/cubic"
keywords = ["cli", "vm"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "^4", features = ["derive"] }
reqwest = { version = "^0", features = ["blocking"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_yaml = "^0"
libc = "^0"
regex = "^1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
