name: cubic
version: '0.7.0'
license: GPL-2.0-only
website: https://github.com/cubic-vm/cubic
source-code: https://github.com/cubic-vm/cubic
issues: https://github.com/cubic-vm/cubic/issues
summary: Cubic is a lightweight command line manager for virtual machines.
description: |
  Cubic is a lightweight command line manager for virtual machines with focus on simplicity and security.

  It has a daemon-less and rootless design. All Cubic virtual machines run unprivileged in the user context. Cubic is built on top of QEMU, KVM and cloud-init.
base: core24
platforms:
  amd64:
  arm64:
confinement: strict
parts:
  cubic:
    plugin: rust
    source: .
  runtime-dependencies:
    plugin: nil
    stage-packages:
      - cloud-image-utils
      - openssh-client
      - qemu-system-x86
      - qemu-system-gui
      - qemu-system-modules-spice
      - seabios
      - libvirglrenderer1
    override-build: |
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-ppc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc32
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc64
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/cmake*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/dri*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/gdk*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/gio*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/gli*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/gstreamer*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/gtk*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/icu*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libEGL*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libGL*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libLLVM*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libOpenGL*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libSDL*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libX*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libasound*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libavahi*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libavahi*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libbmp*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libdrm*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libgdk*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libgst*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libgtk*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libicudata*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libjpeg*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libnss*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libogg*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libopus*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libpipewire*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libpulse*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libsensors*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libsharp*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libsnd*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libtiff*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libunwind*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libvorbis*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libvulkan*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libwayland*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libwebp*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libxcb*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libxml*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libxshm*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/spa*
apps:
  cubic:
    extensions: [gnome]
    command: bin/cubic
    plugs:
      - kvm
      - network
      - network-bind
      - home
      - ssh-keys
