name: cubic
version: git
summary: Cubic is a lightweight command line manager for virtual machines
description: |
  Cubic is a lightweight command line manager for virtual machines.
base: core22
confinement: classic
parts:
  cubic:
    plugin: rust
    source: .
apps:
  cubic:
    command: bin/cubic
