name: cubic
version: '0.18.0'
license: MIT OR Apache-2.0
website: https://cubic-vm.org
source-code: https://github.com/cubic-vm/cubic
issues: https://github.com/cubic-vm/cubic/issues
summary: Cubic is a lightweight command line manager for virtual machines.
description: |
  Cubic is a lightweight command line manager for virtual machines with focus on simplicity and security.

  It has a daemon-less and rootless design. All Cubic virtual machines run unprivileged in the user context. Cubic is built on top of QEMU, KVM and cloud-init.
base: core24
platforms:
  amd64:
  arm64:
    build-on:
      - amd64
      - arm64
    build-for:
      - arm64
confinement: strict
parts:
  cubic:
    plugin: rust
    source: .
    rust-cargo-parameters: ["--features", "qemu-sandbox"]
  runtime-dependencies:
    plugin: nil
    stage-packages:
      - genisoimage
      - qemu-utils
      - qemu-system-x86
      - qemu-system-arm
      - qemu-efi-aarch64
      - seabios
    override-build: |
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libicudata*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libgallium*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libLLVM*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-pr-helper
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-io
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-nbd
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-storage-daemon
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-system-x86_64-microvm
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-system-i386
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/qemu-system-arm
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-ppc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc32
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc64
  cleanup:
    after:
      - cubic
      - runtime-dependencies
    plugin: nil
    build-snaps:
      - core24
    override-prime: |
      set -eux
      for snap in "core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
apps:
  cubic:
    command: bin/cubic
    plugs:
      - kvm
      - network
      - network-bind
      - home
      - ssh-keys
    environment:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
