name: cubic
version: git
license: GPL-2.0-only
website: https://github.com/cubic-vm/cubic
source-code: https://github.com/cubic-vm/cubic
issues: https://github.com/cubic-vm/cubic/issues
summary: Cubic is a lightweight command line manager for virtual machines
description: |
  Cubic is a lightweight command line manager for virtual machines.
base: core24
platforms:
  amd64:
  arm64:
confinement: strict
parts:
  cubic:
    plugin: rust
    source: .
    stage-packages:
      - openssl
      - libssl-dev
      - ca-certificates
      - pkg-config
  runtime-dependencies:
    plugin: nil
    stage-packages:
      - bubblewrap
      - cloud-image-utils
      - openssh-client
      - qemu-system-x86
      - seabios
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-ppc
      rm $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc32
      rm $SNAPCRAFT_PART_INSTALL/usr/share/qemu/openbios-sparc64
apps:
  cubic:
    command: bin/cubic
    plugs:
      - kvm
      - network
      - network-bind
