version: '3'

env:
  DOCKER_CMD: docker run --rm -v .:/usr/local/app cubic

tasks:
  build-image:
    cmds:
      - docker build -t cubic .

  format:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo fmt --check

  fix-format:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo fmt

  lint:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo clippy -- -D warnings

  fix-lint:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo clippy --fix --allow-dirty --allow-staged

  test:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo test

  audit:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD cargo audit

  check:
    deps: [format, lint, test, audit]

  fix:
    deps: [fix-format, fix-lint]

  build:
    cmds:
      - $DOCKER_CMD cargo build
