version: '3'

env:
  DOCKER_CMD: docker run --rm -v .:/usr/local/app
  IMAGE: cubic

tasks:
  build-image:
    cmds:
      - docker build -t cubic .

  clean:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo clean

  format:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo fmt --check

  fix-format:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo fmt

  lint:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo clippy -- -D warnings

  fix-lint:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo clippy --fix --allow-dirty --allow-staged

  test:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo test

  audit:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo audit

  update:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo update

  sh:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD -it $IMAGE  bash

  check:
    deps: [format, lint, test, audit]

  fix:
    deps: [fix-format, fix-lint]

  build:
    deps: [build-image]
    cmds:
      - $DOCKER_CMD $IMAGE cargo build
