use crate::image::ImageName;
use std::io;

pub enum Error {
    UnknownCommand,
    UnknownMachine(String),
    MachineNotRunning(String),
    MachineNotStopped(String),
    Start(String),
    Stop(String),
    MachineAlreadyExists(String),
    Io(io::Error),
    UnknownImage(ImageName),
    MissingSshKey,
    InvalidImageName(String),
    UnsetHomeVar,
    InvalidOption(String),
    CannotCopyFile(String, String),
    CannotCopyDir(String, String),
    CannotOpenFile(String),
    CannotCreateFile(String),
    CannotCreateDir(String),
    CannotAccessDir(String),
    CannotWriteDir(String),
    CannotWriteFile(String),
    CannotRemoveFile(String),
    CannotParseFile(String),
    CannotAttach(String),
    InvalidSshTarget(String),
    UserDataCreationFailed(String),
    CannotParseSize(String),
    CannotShrinkDisk(String),
    ImageDownloadFailed(String),
}
