---
name: Pull Request Checks
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    strategy:
      matrix:
        include:
          - check: cargo fmt --check
            cargo: ""

          - check: cargo clippy -- -D warnings
            cargo: ""

          - check: cargo test
            cargo: ""

          - check: cargo audit
            cargo: "cargo-audit"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup toolchain install stable

      - name: Install Tools
        run: sh -c "[ -n \"${{ matrix.cargo }}\" ]  && cargo install ${{ matrix.cargo }} || true"

      - name: Run Check
        run: ${{ matrix.check }}

  lint:
    name: File Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint YAML
        run: yamllint --strict .

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup toolchain install stable

      - name: Build Source Code
        run: cargo build

      - name: Run Source Code
        run: cargo run -- --help
